language: go

os:
  - linux
  - osx

go:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/860de7e374c89032863a
    on_success: change
    on_failure: always
    on_start: never

  email:
    on_success: change
    on_failure: always
